<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NIBLM127.local" failures="1" tests="1" name="org.stockwell.tests.LoginTest" time="11.109" errors="0" timestamp="2024-07-09T14:55:06 IST" skipped="0">
  <testcase classname="org.stockwell.tests.LoginTest" name="verifyLoginPageAsSuperUser" time="11.109">
    <failure message="Failed due to java.lang.NullPointerException: Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&quot; because the return value of &quot;org.stockwell.reportsetup.ExtFactory.getExtent()&quot; is null could not capture the screenshot due to java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed due to java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "org.stockwell.reportsetup.ExtFactory.getExtent()" is null could not capture the screenshot due to java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.testng.Assert.fail(Assert.java:99)
at org.stockwell.tests.TestInfra.failWithScreenShot(TestInfra.java:65)
at org.stockwell.tests.LoginTest.verifyLoginPageAsSuperUser(LoginTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- verifyLoginPageAsSuperUser -->
  <system-out/>
</testsuite> <!-- org.stockwell.tests.LoginTest -->
