<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NIBLM127.local" failures="1" tests="1" name="Test" time="11.151" errors="0" timestamp="2024-07-09T14:55:06 IST">
  <testcase classname="org.stockwell.tests.LoginTest" name="verifyLoginPageAsSuperUser" time="8.507">
    <failure type="java.lang.AssertionError" message="Failed due to java.lang.NullPointerException: Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because the return value of &amp;quot;org.stockwell.reportsetup.ExtFactory.getExtent()&amp;quot; is null could not capture the screenshot due to java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1">
      <![CDATA[java.lang.AssertionError: Failed due to java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "org.stockwell.reportsetup.ExtFactory.getExtent()" is null could not capture the screenshot due to java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.stockwell.tests.TestInfra.failWithScreenShot(TestInfra.java:65)
at org.stockwell.tests.LoginTest.verifyLoginPageAsSuperUser(LoginTest.java:32)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginPageAsSuperUser -->
</testsuite> <!-- Test -->
